import type {
  ArmorLocationTypes,
  ArmorLocationValues,
  ArmorTemplate,
  ImportedArmorSourceMetadata,
  MaterialType,
} from "@glantri/domain/equipment";

type ImportedArmorSeed = {
  armorActivityModifier: number | null;
  armorRating: number;
  baseEncumbrance: number;
  componentNames: string[];
  componentRows: number[];
  defaultMaterial: MaterialType;
  finishedRow: number;
  id: string;
  locationTypes: ArmorLocationTypes | null;
  locationValues: ArmorLocationValues;
  movementFactor: number;
  name: string;
  perceptionModifier: number | null;
  subtype: string;
  tags: string[];
  typeRow: number | null;
  warnings: string[] | null;
};

const sourceColumns = {
  name: "A",
  encumbranceFactor: "B",
  movementFactor: "C",
  head: "D",
  frontArm: "E",
  chest: "F",
  backArm: "G",
  abdomen: "H",
  frontThigh: "I",
  frontFoot: "J",
  backThigh: "K",
  backFoot: "L",
  generalArmor: "M",
  armorActivityModifier: "N",
  perceptionModifier: "O",
  dropdown: "R",
} as const;

function buildSourceMetadata(seed: ImportedArmorSeed): ImportedArmorSourceMetadata {
  const startRow = seed.componentRows[0] ?? seed.finishedRow;
  const endRow = seed.typeRow ?? seed.finishedRow;

  return {
    workbook: "Themistogenes 1.07.xlsx",
    sheet: "Armor",
    finishedRow: seed.finishedRow,
    typeRow: seed.typeRow,
    componentRows: seed.componentRows.length > 0 ? seed.componentRows : null,
    sourceRange: `Armor!A${startRow}:R${endRow}`,
    sourceColumns,
    rawRows: {
      [String(seed.finishedRow)]: {
        A: seed.name,
        R: seed.name,
      },
      ...(seed.typeRow
        ? {
            [String(seed.typeRow)]: {
              A: `Type: ${seed.name}`,
            },
          }
        : {}),
      ...Object.fromEntries(
        seed.componentRows.map((rowNumber, index) => [
          String(rowNumber),
          {
            A: seed.componentNames[index] ?? `Armor component ${rowNumber}`,
          },
        ]),
      ),
    },
  };
}

function buildArmorTemplate(seed: ImportedArmorSeed): ArmorTemplate {
  return {
    id: seed.id,
    category: "armor",
    name: seed.name,
    subtype: seed.subtype,
    tags: seed.tags,
    specificityTypeDefault: "generic",
    defaultMaterial: seed.defaultMaterial,
    baseEncumbrance: seed.baseEncumbrance,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    armorRating: seed.armorRating,
    mobilityPenalty: seed.movementFactor,
    armorActivityModifier: seed.armorActivityModifier,
    movementFactor: seed.movementFactor,
    perceptionModifier: seed.perceptionModifier,
    locationValues: seed.locationValues,
    locationTypes: seed.locationTypes,
    componentProfiles:
      seed.componentNames.length > 0
        ? seed.componentNames.map((name, index) => ({
            name,
            sourceMetadata: {
              workbook: "Themistogenes 1.07.xlsx",
              sheet: "Armor",
              finishedRow: seed.componentRows[index] ?? seed.finishedRow,
              typeRow: null,
              componentRows: null,
              sourceRange: `Armor!A${seed.componentRows[index] ?? seed.finishedRow}:R${seed.componentRows[index] ?? seed.finishedRow}`,
              sourceColumns,
              rawRows: {
                [String(seed.componentRows[index] ?? seed.finishedRow)]: {
                  A: name,
                },
              },
            },
          }))
        : null,
    sourceMetadata: buildSourceMetadata(seed),
    importWarnings: seed.warnings,
  };
}

const importedArmorSeeds: ImportedArmorSeed[] = [
  {
    id: "armor-template-leather-cloth",
    name: "Leather/Cloth",
    subtype: "leather-cloth",
    tags: ["armor", "themistogenes-import", "other", "leather", "cloth"],
    defaultMaterial: "other",
    baseEncumbrance: 0.4444444444,
    movementFactor: 0.1777777778,
    armorRating: 1.777777778,
    armorActivityModifier: 0,
    perceptionModifier: null,
    locationValues: { head: 0, frontArm: 2, chest: 2, backArm: 2, abdomen: 2, frontThigh: 2, frontFoot: 2, backThigh: 2, backFoot: 2 },
    locationTypes: { head: "A", frontArm: "A", chest: "B", backArm: "A", abdomen: "B", frontThigh: "A", frontFoot: "A", backThigh: "A", backFoot: "A", generalArmor: "A" },
    componentNames: [],
    finishedRow: 3,
    typeRow: 4,
    componentRows: [],
    warnings: ["Leather/Cloth: workbook name spans more than one material family, so default material stays 'other'."],
  },
  {
    id: "armor-template-leather-jerkin",
    name: "Leather Jerkin",
    subtype: "leather-jerkin",
    tags: ["armor", "themistogenes-import", "leather", "set"],
    defaultMaterial: "leather",
    baseEncumbrance: 0.6666666667,
    movementFactor: 0.2666666667,
    armorRating: 2.666666667,
    armorActivityModifier: 0,
    perceptionModifier: 0,
    locationValues: { head: 0, frontArm: 3, chest: 3, backArm: 3, abdomen: 3, frontThigh: 3, frontFoot: 3, backThigh: 3, backFoot: 3 },
    locationTypes: { head: "A", frontArm: "B", chest: "B", backArm: "B", abdomen: "B", frontThigh: "B", frontFoot: "B", backThigh: "B", backFoot: "B", generalArmor: "B" },
    componentNames: ["Gauntlets", "Light  Boots"],
    finishedRow: 8,
    typeRow: 9,
    componentRows: [6, 7],
    warnings: null,
  },
  {
    id: "armor-template-studded-jerkin",
    name: "Studded Jerkin",
    subtype: "studded-jerkin",
    tags: ["armor", "themistogenes-import", "leather", "set"],
    defaultMaterial: "leather",
    baseEncumbrance: 1,
    movementFactor: 0.4,
    armorRating: 4,
    armorActivityModifier: 0,
    perceptionModifier: 0,
    locationValues: { head: 0, frontArm: 5, chest: 5, backArm: 5, abdomen: 5, frontThigh: 5, frontFoot: 3, backThigh: 5, backFoot: 3 },
    locationTypes: { head: "A", frontArm: "C", chest: "C", backArm: "C", abdomen: "C", frontThigh: "C", frontFoot: "B", backThigh: "C", backFoot: "B", generalArmor: "C" },
    componentNames: ["Gauntlets", "Light  Boots"],
    finishedRow: 13,
    typeRow: 14,
    componentRows: [11, 12],
    warnings: null,
  },
  {
    id: "armor-template-cloth",
    name: "Cloth",
    subtype: "cloth",
    tags: ["armor", "themistogenes-import", "cloth"],
    defaultMaterial: "cloth",
    baseEncumbrance: 1.266666667,
    movementFactor: 1.166666667,
    armorRating: 4.444444444,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 4, frontArm: 5, chest: 5, backArm: 5, abdomen: 5, frontThigh: 5, frontFoot: 3, backThigh: 5, backFoot: 3 },
    locationTypes: { head: "A", frontArm: "A", chest: "A", backArm: "A", abdomen: "A", frontThigh: "A", frontFoot: "A", backThigh: "A", backFoot: "A", generalArmor: null },
    componentNames: ["Fur Stuffing", "Light  Boots"],
    finishedRow: 18,
    typeRow: 19,
    componentRows: [16, 17],
    warnings: null,
  },
  {
    id: "armor-template-leather-armor",
    name: "Leather Armor",
    subtype: "leather-armor",
    tags: ["armor", "themistogenes-import", "leather", "set"],
    defaultMaterial: "leather",
    baseEncumbrance: 1.433333333,
    movementFactor: 1.333333333,
    armorRating: 5.111111111,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 4, frontArm: 6, chest: 6, backArm: 6, abdomen: 6, frontThigh: 6, frontFoot: 3, backThigh: 6, backFoot: 3 },
    locationTypes: { head: "A", frontArm: "C", chest: "C", backArm: "C", abdomen: "C", frontThigh: "C", frontFoot: "B", backThigh: "C", backFoot: "B", generalArmor: "B" },
    componentNames: ["Fur Stuffing", "Light  Boots"],
    finishedRow: 23,
    typeRow: 24,
    componentRows: [21, 22],
    warnings: null,
  },
  {
    id: "armor-template-cloak",
    name: "Cloak",
    subtype: "cloak",
    tags: ["armor", "themistogenes-import", "cloth", "set"],
    defaultMaterial: "cloth",
    baseEncumbrance: 0.2222222222,
    movementFactor: 0.08888888889,
    armorRating: 0.8888888889,
    armorActivityModifier: 0,
    perceptionModifier: null,
    locationValues: { head: 0, frontArm: 1, chest: 1, backArm: 1, abdomen: 1, frontThigh: 1, frontFoot: 1, backThigh: 1, backFoot: 1 },
    locationTypes: { head: "A", frontArm: "A", chest: "A", backArm: "A", abdomen: "A", frontThigh: "A", frontFoot: "A", backThigh: "A", backFoot: "A", generalArmor: "A" },
    componentNames: [],
    finishedRow: 26,
    typeRow: 27,
    componentRows: [],
    warnings: null,
  },
  {
    id: "armor-template-heaavy-cloak",
    name: "Heaavy Cloak",
    subtype: "heaavy-cloak",
    tags: ["armor", "themistogenes-import", "cloth", "set"],
    defaultMaterial: "cloth",
    baseEncumbrance: 0.4444444444,
    movementFactor: 0.1777777778,
    armorRating: 1.777777778,
    armorActivityModifier: 0,
    perceptionModifier: null,
    locationValues: { head: 0, frontArm: 2, chest: 2, backArm: 2, abdomen: 2, frontThigh: 2, frontFoot: 2, backThigh: 2, backFoot: 2 },
    locationTypes: { head: "A", frontArm: "B", chest: "B", backArm: "B", abdomen: "B", frontThigh: "B", frontFoot: "B", backThigh: "B", backFoot: "B", generalArmor: "B" },
    componentNames: [],
    finishedRow: 29,
    typeRow: 30,
    componentRows: [],
    warnings: null,
  },
  {
    id: "armor-template-ring-mail-shirt",
    name: "Ring Mail Shirt",
    subtype: "ring-mail-shirt",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.605555556,
    movementFactor: 1.077777778,
    armorRating: 5.666666667,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 7, frontArm: 7, chest: 7, backArm: 7, abdomen: 7, frontThigh: 5, frontFoot: 3, backThigh: 5, backFoot: 3 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "C", frontFoot: "B", backThigh: "C", backFoot: "B", generalArmor: "C" },
    componentNames: ["Helmet", "Leather Padding", "Light  Boots"],
    finishedRow: 35,
    typeRow: 36,
    componentRows: [32, 33, 34],
    warnings: null,
  },
  {
    id: "armor-template-ring-mail-coat",
    name: "Ring Mail Coat",
    subtype: "ring-mail-coat",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.816358025,
    movementFactor: 1.444444444,
    armorRating: 6.555555556,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 7, frontArm: 7, chest: 7, backArm: 7, abdomen: 7, frontThigh: 7, frontFoot: 5, backThigh: 7, backFoot: 5 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "D", frontFoot: "D", backThigh: "D", backFoot: "D", generalArmor: "D" },
    componentNames: ["Helmet", "Leather Padding", "Heavy Boots"],
    finishedRow: 41,
    typeRow: 42,
    componentRows: [38, 39, 40],
    warnings: null,
  },
  {
    id: "armor-template-scale-mail-shirt",
    name: "Scale Mail Shirt",
    subtype: "scale-mail-shirt",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail", "scale"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.617901235,
    movementFactor: 1.505555556,
    armorRating: 5.888888889,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 9, frontArm: 8, chest: 8, backArm: 8, abdomen: 8, frontThigh: 3, frontFoot: 3, backThigh: 3, backFoot: 3 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "B", frontFoot: "B", backThigh: "B", backFoot: "B", generalArmor: "C" },
    componentNames: ["Helmet", "Leather Padding", "Light  Boots"],
    finishedRow: 47,
    typeRow: 48,
    componentRows: [44, 45, 46],
    warnings: null,
  },
  {
    id: "armor-template-scale-mail-coat",
    name: "Scale Mail Coat",
    subtype: "scale-mail-coat",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail", "scale"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.938580247,
    movementFactor: 1.761111111,
    armorRating: 7,
    armorActivityModifier: 0,
    perceptionModifier: -2,
    locationValues: { head: 9, frontArm: 8, chest: 8, backArm: 8, abdomen: 8, frontThigh: 6, frontFoot: 5, backThigh: 6, backFoot: 5 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "C", frontFoot: "C", backThigh: "C", backFoot: "C", generalArmor: "D" },
    componentNames: ["Helmet", "Leather Padding", "Heavy Boots"],
    finishedRow: 53,
    typeRow: 54,
    componentRows: [50, 51, 52],
    warnings: null,
  },
  {
    id: "armor-template-light-mail-coat-1",
    name: "Light Mail Coat 1",
    subtype: "light-mail-coat-1",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.761111111,
    movementFactor: 1.15,
    armorRating: 6.777777778,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 9, frontArm: 7, chest: 7, backArm: 7, abdomen: 7, frontThigh: 7, frontFoot: 5, backThigh: 7, backFoot: 5 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "D", frontFoot: "C", backThigh: "D", backFoot: "C", generalArmor: "D" },
    componentNames: ["Helmet", "Leather Padding", "Boots"],
    finishedRow: 59,
    typeRow: 60,
    componentRows: [56, 57, 58],
    warnings: null,
  },
  {
    id: "armor-template-light-mail-coat-2",
    name: "Light Mail Coat 2",
    subtype: "light-mail-coat-2",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.872222222,
    movementFactor: 1.372222222,
    armorRating: 7.222222222,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 9, frontArm: 7, chest: 7, backArm: 7, abdomen: 7, frontThigh: 7, frontFoot: 7, backThigh: 7, backFoot: 7 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "D", frontFoot: "D", backThigh: "D", backFoot: "D", generalArmor: "D" },
    componentNames: ["Helmet", "Felt Padding", "Mail Leggings", "Boots"],
    finishedRow: 66,
    typeRow: 67,
    componentRows: [62, 63, 64, 65],
    warnings: null,
  },
  {
    id: "armor-template-medium-mail-coat-1",
    name: "Medium Mail Coat 1",
    subtype: "medium-mail-coat-1",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail"],
    defaultMaterial: "steel",
    baseEncumbrance: 2.094444444,
    movementFactor: 1.6,
    armorRating: 8.111111111,
    armorActivityModifier: 0,
    perceptionModifier: -2,
    locationValues: { head: 9, frontArm: 9, chest: 9, backArm: 9, abdomen: 9, frontThigh: 9, frontFoot: 5, backThigh: 9, backFoot: 5 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "D", frontFoot: "C", backThigh: "D", backFoot: "C", generalArmor: "D" },
    componentNames: ["Helmet", "Leather Padding", "Boots"],
    finishedRow: 72,
    typeRow: 73,
    componentRows: [69, 70, 71],
    warnings: null,
  },
  {
    id: "armor-template-medium-mail-coat-2",
    name: "Medium Mail Coat 2",
    subtype: "medium-mail-coat-2",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail"],
    defaultMaterial: "steel",
    baseEncumbrance: 2.205555556,
    movementFactor: 1.827777778,
    armorRating: 8.555555556,
    armorActivityModifier: 0,
    perceptionModifier: -2,
    locationValues: { head: 9, frontArm: 9, chest: 9, backArm: 9, abdomen: 9, frontThigh: 9, frontFoot: 7, backThigh: 9, backFoot: 7 },
    locationTypes: { head: "D", frontArm: "D", chest: "D", backArm: "D", abdomen: "D", frontThigh: "D", frontFoot: "D", backThigh: "D", backFoot: "D", generalArmor: "D" },
    componentNames: ["Helmet", "Felt Padding", "Mail Leggings", "Boots"],
    finishedRow: 79,
    typeRow: 80,
    componentRows: [75, 76, 77, 78],
    warnings: null,
  },
  {
    id: "armor-template-elven-mail-coat",
    name: "Elven Mail Coat",
    subtype: "elven-mail-coat",
    tags: ["armor", "themistogenes-import", "steel", "set", "mail"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.606666667,
    movementFactor: 1.421666667,
    armorRating: 10.11111111,
    armorActivityModifier: 0,
    perceptionModifier: -2,
    locationValues: { head: 15, frontArm: 11, chest: 11, backArm: 11, abdomen: 11, frontThigh: 9, frontFoot: 7, backThigh: 9, backFoot: 7 },
    locationTypes: { head: "E", frontArm: "E", chest: "E", backArm: "E", abdomen: "E", frontThigh: "D", frontFoot: "D", backThigh: "D", backFoot: "D", generalArmor: "E" },
    componentNames: ["Helmet", "Felt Padding", "Mail Leggings", "Boots"],
    finishedRow: 86,
    typeRow: 87,
    componentRows: [82, 83, 84, 85],
    warnings: null,
  },
  {
    id: "armor-template-thyasian-legionnaire",
    name: "Thyasian Legionnaire",
    subtype: "thyasian-legionnaire",
    tags: ["armor", "themistogenes-import", "steel"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.305555556,
    movementFactor: 1.175,
    armorRating: 5.222222222,
    armorActivityModifier: 0,
    perceptionModifier: -1,
    locationValues: { head: 7, frontArm: 5, chest: 7, backArm: 5, abdomen: 7, frontThigh: 5, frontFoot: 3, backThigh: 5, backFoot: 3 },
    locationTypes: { head: "D", frontArm: "C", chest: "D", backArm: "C", abdomen: "D", frontThigh: "C", frontFoot: "C", backThigh: "C", backFoot: "C", generalArmor: "C" },
    componentNames: ["Helmet"],
    finishedRow: 91,
    typeRow: 92,
    componentRows: [90],
    warnings: null,
  },
  {
    id: "armor-template-thyasian-guard-officer",
    name: "Thyasian Guard/Officer",
    subtype: "thyasian-guard-officer",
    tags: ["armor", "themistogenes-import", "steel"],
    defaultMaterial: "steel",
    baseEncumbrance: 1.638888889,
    movementFactor: 1.475,
    armorRating: 6.555555556,
    armorActivityModifier: 0,
    perceptionModifier: -2,
    locationValues: { head: 9, frontArm: 7, chest: 11, backArm: 7, abdomen: 9, frontThigh: 5, frontFoot: 3, backThigh: 5, backFoot: 3 },
    locationTypes: { head: "D", frontArm: "D", chest: "E", backArm: "D", abdomen: "D", frontThigh: "C", frontFoot: "C", backThigh: "C", backFoot: "C", generalArmor: "D" },
    componentNames: ["Helmet"],
    finishedRow: 95,
    typeRow: 96,
    componentRows: [94],
    warnings: null,
  },
  {
    id: "armor-template-breastplate-backplate",
    name: "Breastplate/Backplate",
    subtype: "breastplate-backplate",
    tags: ["armor", "themistogenes-import", "steel", "plate"],
    defaultMaterial: "steel",
    baseEncumbrance: 2.5,
    movementFactor: 2.351851852,
    armorRating: 9.222222222,
    armorActivityModifier: 0,
    perceptionModifier: -2,
    locationValues: { head: 11, frontArm: 10, chest: 13, backArm: 10, abdomen: 9, frontThigh: 9, frontFoot: 7, backThigh: 9, backFoot: 7 },
    locationTypes: { head: "E", frontArm: "E", chest: "E", backArm: "E", abdomen: "D", frontThigh: "D", frontFoot: "D", backThigh: "D", backFoot: "D", generalArmor: "D" },
    componentNames: ["Cuisse & Greaves", "Vambrace", "Gauntlets", "Helmet", "Leather Padding", "Light Boots"],
    finishedRow: 104,
    typeRow: 105,
    componentRows: [98, 99, 100, 101, 102, 103],
    warnings: null,
  },
  {
    id: "armor-template-light-plate-armor",
    name: "Light Plate Armor",
    subtype: "light-plate-armor",
    tags: ["armor", "themistogenes-import", "steel", "set", "plate"],
    defaultMaterial: "steel",
    baseEncumbrance: 2.25,
    movementFactor: 2.45,
    armorRating: 9,
    armorActivityModifier: 0,
    perceptionModifier: -3,
    locationValues: { head: 11, frontArm: 9, chest: 11, backArm: 9, abdomen: 11, frontThigh: 8, frontFoot: 7, backThigh: 8, backFoot: 7 },
    locationTypes: { head: "E", frontArm: "D", chest: "E", backArm: "D", abdomen: "E", frontThigh: "D", frontFoot: "D", backThigh: "D", backFoot: "D", generalArmor: "D" },
    componentNames: ["Knights Helmet"],
    finishedRow: 108,
    typeRow: 109,
    componentRows: [107],
    warnings: null,
  },
  {
    id: "armor-template-field-plate-armor",
    name: "Field Plate Armor",
    subtype: "field-plate-armor",
    tags: ["armor", "themistogenes-import", "steel", "set", "plate"],
    defaultMaterial: "steel",
    baseEncumbrance: 2.916666667,
    movementFactor: 3.175,
    armorRating: 11.66666667,
    armorActivityModifier: 0,
    perceptionModifier: -5,
    locationValues: { head: 17, frontArm: 11, chest: 13, backArm: 11, abdomen: 13, frontThigh: 11, frontFoot: 9, backThigh: 11, backFoot: 9 },
    locationTypes: { head: "E", frontArm: "E", chest: "E", backArm: "E", abdomen: "E", frontThigh: "E", frontFoot: "D", backThigh: "E", backFoot: "D", generalArmor: "E" },
    componentNames: ["Knights Helmet"],
    finishedRow: 112,
    typeRow: 113,
    componentRows: [111],
    warnings: null,
  },
  {
    id: "armor-template-full-plate-armor",
    name: "Full Plate Armor",
    subtype: "full-plate-armor",
    tags: ["armor", "themistogenes-import", "steel", "set", "plate"],
    defaultMaterial: "steel",
    baseEncumbrance: 3.555555556,
    movementFactor: 4.183333333,
    armorRating: 14.22222222,
    armorActivityModifier: -1,
    perceptionModifier: -6,
    locationValues: { head: 20, frontArm: 13, chest: 15, backArm: 13, abdomen: 15, frontThigh: 13, frontFoot: 13, backThigh: 13, backFoot: 13 },
    locationTypes: { head: "E", frontArm: "E", chest: "E", backArm: "E", abdomen: "E", frontThigh: "E", frontFoot: "E", backThigh: "E", backFoot: "E", generalArmor: "E" },
    componentNames: ["Knights Helmet"],
    finishedRow: 116,
    typeRow: 117,
    componentRows: [115],
    warnings: null,
  },
];

const importedArmorTemplates = importedArmorSeeds.map(buildArmorTemplate);

const legacyCompatibilityArmorTemplates: ArmorTemplate[] = [
  {
    id: "armor-template-mail-hauberk",
    category: "armor",
    name: "Mail Hauberk",
    subtype: "mail",
    tags: ["armor", "medium", "mail", "legacy-compatibility"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 24,
    baseValue: null,
    armorRating: 3,
    mobilityPenalty: 1,
    rulesNotes: "Legacy compatibility armor template kept for older records.",
    roleplayNotes: null,
  },
];

export const armorTemplates: ArmorTemplate[] = [
  ...importedArmorTemplates,
  ...legacyCompatibilityArmorTemplates,
];

export const armorTemplatesById = Object.fromEntries(
  armorTemplates.map((template) => [template.id, template]),
);
