import type { ShieldTemplate } from "@glantri/domain/equipment";

const importedShieldTemplates: ShieldTemplate[] = [
  {
    id: "shield-template-small-shield",
    category: "shield",
    name: "Small shield",
    subtype: "small",
    tags: ["shield", "small", "wood", "themistogenes-import"],
    specificityTypeDefault: "generic",
    defaultMaterial: "wood",
    baseEncumbrance: 3,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponSkill: "Brawling",
    handlingClass: "one_handed",
    attackModes: [
      {
        id: "mode-1",
        label: "Strike",
        canonicalMeleeMode: "strike",
        isPrimaryAttack: true,
        damageClass: "blunt",
        ob: 0,
        obRaw: "0.0",
        dmb: 0,
        dmbRaw: "0.0",
        crit: "AC",
        secondCrit: null,
        armorModifier: null,
        provenance: "imported",
        notes: null,
      },
    ],
    primeAttackType: "Strike",
    primaryAttackType: "Strike",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 3,
    initiative: 0,
    range: "1.0",
    armorMod1: null,
    armorMod2: null,
    crit1: "AC",
    crit2: null,
    secondCrit: null,
    shieldBonus: 3,
    defensiveValue: 3,
    movementModifier: 1,
    offensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Weapon1",
      row: 37,
      sourceRange: "Weapon1!A37:Q37",
      sourceColumns: {
        name: "A",
        skill: "B",
        primaryAttackLabel: "C",
        ob1: "D",
        dmb1: "E",
        ob2: "F",
        dmb2: "G",
        parry: "H",
        initiative: "I",
        range: "J",
        armorMod1: "K",
        armorMod2: "L",
        crit1: "M",
        crit2: "N",
        encumbrance: "O",
        defensiveValue: "P",
        secondCrit: "Q",
      },
      rawRow: {
        A: "Small shield",
        B: "Brawling",
        C: "Strike",
        D: "0.0",
        E: "0.0",
        F: "",
        G: "",
        H: "3.0",
        I: "0.0",
        J: "1.0",
        K: "N/A",
        L: "",
        M: "AC",
        N: "",
        O: "Var",
        P: "3.0",
      },
    },
    defensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Shields",
      row: 3,
      sourceRange: "Shields!A3:F3",
      sourceColumns: {
        name: "A",
        defensiveValue: "B",
        encumbrance: "C",
        movementModifier: "D",
        offensiveWeaponName: "E",
        parry: "F",
      },
      rawRow: {
        A: "Small shield",
        B: "3.0",
        C: "3.0",
        D: "1.0",
        E: "Small shield",
        F: "3.0",
      },
    },
    importWarnings: [
      "Small shield: offensive armor modifier is marked N/A in Weapon1 and stays empty.",
    ],
  },
  {
    id: "shield-template-small-metal-shield",
    category: "shield",
    name: "Small metal shield",
    subtype: "small_metal",
    tags: ["shield", "small", "steel", "themistogenes-import"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 5,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponSkill: "Brawling",
    handlingClass: "one_handed",
    attackModes: [
      {
        id: "mode-1",
        label: "Strike",
        canonicalMeleeMode: "strike",
        isPrimaryAttack: true,
        damageClass: "blunt",
        ob: 0,
        obRaw: "0.0",
        dmb: 0,
        dmbRaw: "0.0",
        crit: "AC",
        secondCrit: null,
        armorModifier: null,
        provenance: "imported",
        notes: null,
      },
    ],
    primeAttackType: "Strike",
    primaryAttackType: "Strike",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 3,
    initiative: 0,
    range: "1.0",
    armorMod1: null,
    armorMod2: null,
    crit1: "AC",
    crit2: null,
    secondCrit: null,
    shieldBonus: 3,
    defensiveValue: 3,
    movementModifier: 1,
    offensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Weapon1",
      row: 37,
      sourceRange: "Weapon1!A37:Q37",
      sourceColumns: {
        name: "A",
        skill: "B",
        primaryAttackLabel: "C",
        ob1: "D",
        dmb1: "E",
        ob2: "F",
        dmb2: "G",
        parry: "H",
        initiative: "I",
        range: "J",
        armorMod1: "K",
        armorMod2: "L",
        crit1: "M",
        crit2: "N",
        encumbrance: "O",
        defensiveValue: "P",
        secondCrit: "Q",
      },
      rawRow: {
        A: "Small shield",
        B: "Brawling",
        C: "Strike",
        D: "0.0",
        E: "0.0",
        F: "",
        G: "",
        H: "3.0",
        I: "0.0",
        J: "1.0",
        K: "N/A",
        L: "",
        M: "AC",
        N: "",
        O: "Var",
        P: "3.0",
      },
    },
    defensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Shields",
      row: 4,
      sourceRange: "Shields!A4:F4",
      sourceColumns: {
        name: "A",
        defensiveValue: "B",
        encumbrance: "C",
        movementModifier: "D",
        offensiveWeaponName: "E",
        parry: "F",
      },
      rawRow: {
        A: "Small metal shield",
        B: "3.0",
        C: "5.0",
        D: "1.0",
        E: "Small shield",
        F: "3.0",
      },
    },
    importWarnings: [
      "Small metal shield: offensive armor modifier is marked N/A in Weapon1 and stays empty.",
    ],
  },
  {
    id: "shield-template-medium-shield",
    category: "shield",
    name: "Medium shield",
    subtype: "medium",
    tags: ["shield", "medium", "wood", "themistogenes-import"],
    specificityTypeDefault: "generic",
    defaultMaterial: "wood",
    baseEncumbrance: 12,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponSkill: "Brawling",
    handlingClass: "one_handed",
    attackModes: [
      {
        id: "mode-1",
        label: "Strike",
        canonicalMeleeMode: "strike",
        isPrimaryAttack: true,
        damageClass: "blunt",
        ob: 0,
        obRaw: "0.0",
        dmb: 0,
        dmbRaw: "0.0",
        crit: "AC",
        secondCrit: null,
        armorModifier: null,
        provenance: "imported",
        notes: null,
      },
    ],
    primeAttackType: "Strike",
    primaryAttackType: "Strike",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 5,
    initiative: 0,
    range: "1.0",
    armorMod1: null,
    armorMod2: null,
    crit1: "AC",
    crit2: null,
    secondCrit: null,
    shieldBonus: 5,
    defensiveValue: 5,
    movementModifier: 2,
    offensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Weapon1",
      row: 38,
      sourceRange: "Weapon1!A38:Q38",
      sourceColumns: {
        name: "A",
        skill: "B",
        primaryAttackLabel: "C",
        ob1: "D",
        dmb1: "E",
        ob2: "F",
        dmb2: "G",
        parry: "H",
        initiative: "I",
        range: "J",
        armorMod1: "K",
        armorMod2: "L",
        crit1: "M",
        crit2: "N",
        encumbrance: "O",
        defensiveValue: "P",
        secondCrit: "Q",
      },
      rawRow: {
        A: "Medium shield",
        B: "Brawling",
        C: "Strike",
        D: "0.0",
        E: "0.0",
        F: "",
        G: "",
        H: "5.0",
        I: "0.0",
        J: "1.0",
        K: "N/A",
        L: "",
        M: "AC",
        N: "",
        O: "Var",
        P: "5.0",
      },
    },
    defensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Shields",
      row: 5,
      sourceRange: "Shields!A5:F5",
      sourceColumns: {
        name: "A",
        defensiveValue: "B",
        encumbrance: "C",
        movementModifier: "D",
        offensiveWeaponName: "E",
        parry: "F",
      },
      rawRow: {
        A: "Medium shield",
        B: "5.0",
        C: "12.0",
        D: "2.0",
        E: "Medium shield",
        F: "5.0",
      },
    },
    importWarnings: [
      "Medium shield: offensive armor modifier is marked N/A in Weapon1 and stays empty.",
    ],
  },
  {
    id: "shield-template-medium-metal-shield",
    category: "shield",
    name: "Medium metal shield",
    subtype: "medium_metal",
    tags: ["shield", "medium", "steel", "themistogenes-import"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 15,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponSkill: "Brawling",
    handlingClass: "one_handed",
    attackModes: [
      {
        id: "mode-1",
        label: "Strike",
        canonicalMeleeMode: "strike",
        isPrimaryAttack: true,
        damageClass: "blunt",
        ob: 0,
        obRaw: "0.0",
        dmb: 0,
        dmbRaw: "0.0",
        crit: "AC",
        secondCrit: null,
        armorModifier: null,
        provenance: "imported",
        notes: null,
      },
    ],
    primeAttackType: "Strike",
    primaryAttackType: "Strike",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 5,
    initiative: 0,
    range: "1.0",
    armorMod1: null,
    armorMod2: null,
    crit1: "AC",
    crit2: null,
    secondCrit: null,
    shieldBonus: 5,
    defensiveValue: 5,
    movementModifier: 2,
    offensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Weapon1",
      row: 38,
      sourceRange: "Weapon1!A38:Q38",
      sourceColumns: {
        name: "A",
        skill: "B",
        primaryAttackLabel: "C",
        ob1: "D",
        dmb1: "E",
        ob2: "F",
        dmb2: "G",
        parry: "H",
        initiative: "I",
        range: "J",
        armorMod1: "K",
        armorMod2: "L",
        crit1: "M",
        crit2: "N",
        encumbrance: "O",
        defensiveValue: "P",
        secondCrit: "Q",
      },
      rawRow: {
        A: "Medium shield",
        B: "Brawling",
        C: "Strike",
        D: "0.0",
        E: "0.0",
        F: "",
        G: "",
        H: "5.0",
        I: "0.0",
        J: "1.0",
        K: "N/A",
        L: "",
        M: "AC",
        N: "",
        O: "Var",
        P: "5.0",
      },
    },
    defensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Shields",
      row: 6,
      sourceRange: "Shields!A6:F6",
      sourceColumns: {
        name: "A",
        defensiveValue: "B",
        encumbrance: "C",
        movementModifier: "D",
        offensiveWeaponName: "E",
        parry: "F",
      },
      rawRow: {
        A: "Medium metal shield",
        B: "5.0",
        C: "15.0",
        D: "2.0",
        E: "Medium shield",
        F: "5.0",
      },
    },
    importWarnings: [
      "Medium metal shield: offensive armor modifier is marked N/A in Weapon1 and stays empty.",
    ],
  },
  {
    id: "shield-template-large-shield",
    category: "shield",
    name: "Large shield",
    subtype: "large",
    tags: ["shield", "large", "wood", "themistogenes-import"],
    specificityTypeDefault: "generic",
    defaultMaterial: "wood",
    baseEncumbrance: 24,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponSkill: "Brawling",
    handlingClass: "one_handed",
    attackModes: [
      {
        id: "mode-1",
        label: "Strike",
        canonicalMeleeMode: "strike",
        isPrimaryAttack: true,
        damageClass: "blunt",
        ob: 0,
        obRaw: "0.0",
        dmb: 0,
        dmbRaw: "0.0",
        crit: "AC",
        secondCrit: null,
        armorModifier: null,
        provenance: "imported",
        notes: null,
      },
    ],
    primeAttackType: "Strike",
    primaryAttackType: "Strike",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 7,
    initiative: 0,
    range: "1.0",
    armorMod1: null,
    armorMod2: null,
    crit1: "AC",
    crit2: null,
    secondCrit: null,
    shieldBonus: 7,
    defensiveValue: 7,
    movementModifier: 3,
    offensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Weapon1",
      row: 39,
      sourceRange: "Weapon1!A39:Q39",
      sourceColumns: {
        name: "A",
        skill: "B",
        primaryAttackLabel: "C",
        ob1: "D",
        dmb1: "E",
        ob2: "F",
        dmb2: "G",
        parry: "H",
        initiative: "I",
        range: "J",
        armorMod1: "K",
        armorMod2: "L",
        crit1: "M",
        crit2: "N",
        encumbrance: "O",
        defensiveValue: "P",
        secondCrit: "Q",
      },
      rawRow: {
        A: "Large shield",
        B: "Brawling",
        C: "Strike",
        D: "0.0",
        E: "0.0",
        F: "",
        G: "",
        H: "7.0",
        I: "0.0",
        J: "1.0",
        K: "N/A",
        L: "",
        M: "AC",
        N: "",
        O: "Var",
        P: "7.0",
      },
    },
    defensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Shields",
      row: 7,
      sourceRange: "Shields!A7:F7",
      sourceColumns: {
        name: "A",
        defensiveValue: "B",
        encumbrance: "C",
        movementModifier: "D",
        offensiveWeaponName: "E",
        parry: "F",
      },
      rawRow: {
        A: "Large shield",
        B: "7.0",
        C: "24.0",
        D: "3.0",
        E: "Large shield",
        F: "7.0",
      },
    },
    importWarnings: [
      "Large shield: offensive armor modifier is marked N/A in Weapon1 and stays empty.",
    ],
  },
  {
    id: "shield-template-large-metal-shield",
    category: "shield",
    name: "Large metal shield",
    subtype: "large_metal",
    tags: ["shield", "large", "steel", "themistogenes-import"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 28,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponSkill: "Brawling",
    handlingClass: "one_handed",
    attackModes: [
      {
        id: "mode-1",
        label: "Strike",
        canonicalMeleeMode: "strike",
        isPrimaryAttack: true,
        damageClass: "blunt",
        ob: 0,
        obRaw: "0.0",
        dmb: 0,
        dmbRaw: "0.0",
        crit: "AC",
        secondCrit: null,
        armorModifier: null,
        provenance: "imported",
        notes: null,
      },
    ],
    primeAttackType: "Strike",
    primaryAttackType: "Strike",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 7,
    initiative: 0,
    range: "1.0",
    armorMod1: null,
    armorMod2: null,
    crit1: "AC",
    crit2: null,
    secondCrit: null,
    shieldBonus: 7,
    defensiveValue: 7,
    movementModifier: 3,
    offensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Weapon1",
      row: 39,
      sourceRange: "Weapon1!A39:Q39",
      sourceColumns: {
        name: "A",
        skill: "B",
        primaryAttackLabel: "C",
        ob1: "D",
        dmb1: "E",
        ob2: "F",
        dmb2: "G",
        parry: "H",
        initiative: "I",
        range: "J",
        armorMod1: "K",
        armorMod2: "L",
        crit1: "M",
        crit2: "N",
        encumbrance: "O",
        defensiveValue: "P",
        secondCrit: "Q",
      },
      rawRow: {
        A: "Large shield",
        B: "Brawling",
        C: "Strike",
        D: "0.0",
        E: "0.0",
        F: "",
        G: "",
        H: "7.0",
        I: "0.0",
        J: "1.0",
        K: "N/A",
        L: "",
        M: "AC",
        N: "",
        O: "Var",
        P: "7.0",
      },
    },
    defensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Shields",
      row: 8,
      sourceRange: "Shields!A8:F8",
      sourceColumns: {
        name: "A",
        defensiveValue: "B",
        encumbrance: "C",
        movementModifier: "D",
        offensiveWeaponName: "E",
        parry: "F",
      },
      rawRow: {
        A: "Large metal shield",
        B: "7.0",
        C: "28.0",
        D: "3.0",
        E: "Large shield",
        F: "7.0",
      },
    },
    importWarnings: [
      "Large metal shield: offensive armor modifier is marked N/A in Weapon1 and stays empty.",
    ],
  },
  {
    id: "shield-template-tyasian-metal-shield",
    category: "shield",
    name: "Tyasian metal shield",
    subtype: "tyasian_metal",
    tags: ["shield", "large", "steel", "themistogenes-import", "tyasian"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 33,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponSkill: "Brawling",
    handlingClass: "one_handed",
    attackModes: [
      {
        id: "mode-1",
        label: "Strike",
        canonicalMeleeMode: "strike",
        isPrimaryAttack: true,
        damageClass: "blunt",
        ob: 0,
        obRaw: "0.0",
        dmb: 0,
        dmbRaw: "0.0",
        crit: "AC",
        secondCrit: null,
        armorModifier: null,
        provenance: "imported",
        notes: null,
      },
    ],
    primeAttackType: "Strike",
    primaryAttackType: "Strike",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 8,
    initiative: 0,
    range: "1.0",
    armorMod1: null,
    armorMod2: null,
    crit1: "AC",
    crit2: null,
    secondCrit: null,
    shieldBonus: 8,
    defensiveValue: 8,
    movementModifier: 3,
    offensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Weapon1",
      row: 39,
      sourceRange: "Weapon1!A39:Q39",
      sourceColumns: {
        name: "A",
        skill: "B",
        primaryAttackLabel: "C",
        ob1: "D",
        dmb1: "E",
        ob2: "F",
        dmb2: "G",
        parry: "H",
        initiative: "I",
        range: "J",
        armorMod1: "K",
        armorMod2: "L",
        crit1: "M",
        crit2: "N",
        encumbrance: "O",
        defensiveValue: "P",
        secondCrit: "Q",
      },
      rawRow: {
        A: "Large shield",
        B: "Brawling",
        C: "Strike",
        D: "0.0",
        E: "0.0",
        F: "",
        G: "",
        H: "7.0",
        I: "0.0",
        J: "1.0",
        K: "N/A",
        L: "",
        M: "AC",
        N: "",
        O: "Var",
        P: "7.0",
      },
    },
    defensiveSourceMetadata: {
      workbook: "Themistogenes 1.07.xlsx",
      sheet: "Shields",
      row: 9,
      sourceRange: "Shields!A9:F9",
      sourceColumns: {
        name: "A",
        defensiveValue: "B",
        encumbrance: "C",
        movementModifier: "D",
        offensiveWeaponName: "E",
        parry: "F",
      },
      rawRow: {
        A: "Tyasian metal shield",
        B: "8.0",
        C: "33.0",
        D: "3.0",
        E: "Large shield",
        F: "8.0",
      },
    },
    importWarnings: [
      "Tyasian metal shield: offensive armor modifier is marked N/A in Weapon1 and stays empty.",
      "Tyasian metal shield: shield tab defensive value 8 overrides offensive shield-row value 7.",
    ],
  },
];

const legacyCompatibilityShieldTemplates: ShieldTemplate[] = [
  {
    id: "shield-template-buckler",
    category: "shield",
    name: "Buckler",
    subtype: "buckler",
    tags: ["shield", "light", "defense", "legacy-compatibility"],
    specificityTypeDefault: "generic",
    defaultMaterial: "wood",
    baseEncumbrance: 4,
    baseValue: null,
    shieldBonus: 1,
    defensiveValue: 1,
    rulesNotes: "Legacy compatibility shield template kept for older records.",
    roleplayNotes: null,
  },
  {
    id: "shield-template-round-shield",
    category: "shield",
    name: "Round Shield",
    subtype: "round",
    tags: ["shield", "medium", "defense", "legacy-compatibility"],
    specificityTypeDefault: "generic",
    defaultMaterial: "wood",
    baseEncumbrance: 7,
    baseValue: null,
    shieldBonus: 2,
    defensiveValue: 2,
    rulesNotes: "Legacy compatibility shield template kept for older records.",
    roleplayNotes: null,
  },
];

export const shieldTemplates: ShieldTemplate[] = [
  ...importedShieldTemplates,
  ...legacyCompatibilityShieldTemplates,
];

export const shieldTemplatesById = Object.fromEntries(
  shieldTemplates.map((template) => [template.id, template]),
);
