import type { WeaponTemplate } from "@glantri/domain/equipment";

export const weaponTemplates: WeaponTemplate[] = [
  {
    id: "weapon-template-dagger",
    category: "weapon",
    name: "Dagger",
    subtype: "knife",
    tags: ["melee", "edged", "light", "steel-default"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 2,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponClass: "knife",
    weaponSkill: "knife",
    handlingClass: "light",
    primaryAttackType: "thrust",
    secondaryAttackType: "slash",
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 0,
    initiative: 2,
    range: "melee",
    armorMod1: null,
    armorMod2: null,
    crit1: "puncture",
    crit2: null,
    secondCrit: null,
    defensiveValue: null,
    durabilityProfile: {
      maxDurabilityDefault: 8,
      breakThreshold: 0,
      wearSensitivity: "medium",
      edgeSensitive: true,
      shaftSensitive: false,
      notes: null,
    },
  },
  {
    id: "weapon-template-longsword",
    category: "weapon",
    name: "Longsword",
    subtype: "sword",
    tags: ["melee", "edged", "one-handed", "steel-default"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 10,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponClass: "sword",
    weaponSkill: "sword",
    handlingClass: "one_handed",
    primaryAttackType: "slash",
    secondaryAttackType: "thrust",
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 2,
    initiative: 0,
    range: "melee",
    armorMod1: null,
    armorMod2: null,
    crit1: "slash",
    crit2: null,
    secondCrit: null,
    defensiveValue: null,
    durabilityProfile: {
      maxDurabilityDefault: 12,
      breakThreshold: 0,
      wearSensitivity: "medium",
      edgeSensitive: true,
      shaftSensitive: false,
      notes: null,
    },
  },
  {
    id: "weapon-template-mace",
    category: "weapon",
    name: "Mace",
    subtype: "club",
    tags: ["melee", "blunt", "one-handed", "steel-default"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 11,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponClass: "mace",
    weaponSkill: "mace",
    handlingClass: "one_handed",
    primaryAttackType: "blunt",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 1,
    ob2: null,
    dmb2: null,
    parry: 1,
    initiative: -1,
    range: "melee",
    armorMod1: null,
    armorMod2: null,
    crit1: "crush",
    crit2: null,
    secondCrit: null,
    defensiveValue: null,
    durabilityProfile: {
      maxDurabilityDefault: 14,
      breakThreshold: 0,
      wearSensitivity: "low",
      edgeSensitive: false,
      shaftSensitive: false,
      notes: null,
    },
  },
  {
    id: "weapon-template-spear",
    category: "weapon",
    name: "Spear",
    subtype: "polearm",
    tags: ["melee", "thrust", "polearm", "steel-default"],
    specificityTypeDefault: "generic",
    defaultMaterial: "steel",
    baseEncumbrance: 9,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponClass: "spear",
    weaponSkill: "spear",
    handlingClass: "polearm",
    primaryAttackType: "thrust",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: 1,
    initiative: 1,
    range: "melee",
    armorMod1: null,
    armorMod2: null,
    crit1: "puncture",
    crit2: null,
    secondCrit: null,
    defensiveValue: null,
    durabilityProfile: {
      maxDurabilityDefault: 10,
      breakThreshold: 0,
      wearSensitivity: "medium",
      edgeSensitive: true,
      shaftSensitive: true,
      notes: null,
    },
  },
  {
    id: "weapon-template-bow",
    category: "weapon",
    name: "Bow",
    subtype: "bow",
    tags: ["missile", "bow", "wood-default"],
    specificityTypeDefault: "generic",
    defaultMaterial: "wood",
    baseEncumbrance: 8,
    baseValue: null,
    rulesNotes: null,
    roleplayNotes: null,
    weaponClass: "bow",
    weaponSkill: "bow",
    handlingClass: "missile",
    primaryAttackType: "missile",
    secondaryAttackType: null,
    ob1: 0,
    dmb1: 0,
    ob2: null,
    dmb2: null,
    parry: null,
    initiative: 0,
    range: "missile",
    armorMod1: null,
    armorMod2: null,
    crit1: "puncture",
    crit2: null,
    secondCrit: null,
    defensiveValue: null,
    durabilityProfile: {
      maxDurabilityDefault: 8,
      breakThreshold: 0,
      wearSensitivity: "medium",
      edgeSensitive: false,
      shaftSensitive: true,
      notes: null,
    },
  },
];

export const weaponTemplatesById = Object.fromEntries(
  weaponTemplates.map((template) => [template.id, template]),
);
