import type {
  CharacterLoadout,
  EquipmentItem,
  StorageLocation,
} from "@glantri/domain/equipment";
import { createDefaultEquipmentLocations } from "@glantri/content/equipment";

export const sampleCharacterId = "char-themistogenes";

export const sampleLocations: StorageLocation[] = [
  ...createDefaultEquipmentLocations(sampleCharacterId),
  {
    id: `${sampleCharacterId}:loc-home`,
    characterId: sampleCharacterId,
    name: "Home",
    type: "home",
    parentLocationId: null,
    isMobile: false,
    isAccessibleInEncounter: false,
    notes: "Town residence storage.",
  },
];

export const sampleEquipmentItems: EquipmentItem[] = [
  {
    id: "weapon-item-longsword-1",
    characterId: sampleCharacterId,
    templateId: "weapon-template-longsword",
    category: "weapon",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "steel",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-equipped`,
      carryMode: "equipped",
    },
    conditionState: "intact",
    durabilityCurrent: 12,
    durabilityMax: 12,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Ordinary steel longsword.",
    isEquipped: true,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "weapon-item-spear-1",
    characterId: sampleCharacterId,
    templateId: "weapon-template-spear",
    category: "weapon",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "bronze",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-mount`,
      carryMode: "mount",
    },
    conditionState: "intact",
    durabilityCurrent: 10,
    durabilityMax: 10,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Bronze spare spear kept on mount.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "weapon-item-dagger-1",
    characterId: sampleCharacterId,
    templateId: "weapon-template-dagger",
    category: "weapon",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "steel",
    quality: "extraordinary",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-backpack`,
      carryMode: "backpack",
    },
    conditionState: "intact",
    durabilityCurrent: 8,
    durabilityMax: 8,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Extraordinary dagger packed in backpack.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: ["fine-craft"],
  },
  {
    id: "weapon-item-blackfang",
    characterId: sampleCharacterId,
    templateId: "weapon-template-longsword",
    category: "weapon",
    displayName: "Blackfang",
    specificityType: "specific",
    quantity: 1,
    isStackable: false,
    material: "steel",
    quality: "extraordinary",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-home`,
      carryMode: "stored",
    },
    conditionState: "intact",
    durabilityCurrent: 12,
    durabilityMax: 12,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: {
      magicEffects: ["minor warding"],
      damageEffects: ["effective vs undead"],
      roleplayTraits: ["heirloom", "named blade"],
    },
    notes: "Stored heirloom weapon.",
    isEquipped: false,
    isFavorite: true,
    acquiredFrom: "family inheritance",
    statusTags: ["magical"],
  },
  {
    id: "shield-item-round-1",
    characterId: sampleCharacterId,
    templateId: "shield-template-round-shield",
    category: "shield",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "wood",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-equipped`,
      carryMode: "equipped",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Round shield carried on the arm.",
    isEquipped: true,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "shield-item-buckler-1",
    characterId: sampleCharacterId,
    templateId: "shield-template-buckler",
    category: "shield",
    displayName: "Traveler's Buckler",
    specificityType: "specific",
    quantity: 1,
    isStackable: false,
    material: "wood",
    quality: "extraordinary",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-backpack`,
      carryMode: "backpack",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Compact buckler stowed for travel.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "armor-item-jerkin-1",
    characterId: sampleCharacterId,
    templateId: "armor-template-leather-jerkin",
    category: "armor",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "leather",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-equipped`,
      carryMode: "equipped",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Everyday protective jerkin currently worn.",
    isEquipped: true,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "armor-item-mail-1",
    characterId: sampleCharacterId,
    templateId: "armor-template-mail-hauberk",
    category: "armor",
    displayName: "Old Campaign Mail",
    specificityType: "specific",
    quantity: 1,
    isStackable: false,
    material: "steel",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-home`,
      carryMode: "stored",
    },
    conditionState: "worn",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Heavier reserve armor stored at home.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "gear-item-rope-1",
    characterId: sampleCharacterId,
    templateId: "gear-template-rope",
    category: "gear",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "cloth",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-person`,
      carryMode: "on_person",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Travel rope looped at the belt.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "gear-item-lantern-1",
    characterId: sampleCharacterId,
    templateId: "gear-template-lantern",
    category: "gear",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "bronze",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-backpack`,
      carryMode: "backpack",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Packed lantern for travel after dusk.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "gear-item-bedroll-1",
    characterId: sampleCharacterId,
    templateId: "gear-template-bedroll",
    category: "gear",
    displayName: null,
    specificityType: "generic",
    quantity: 1,
    isStackable: false,
    material: "cloth",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-home`,
      carryMode: "stored",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Spare bedroll left at home.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "gear-item-waterskin-1",
    characterId: sampleCharacterId,
    templateId: "gear-template-waterskin",
    category: "gear",
    displayName: "Filled Waterskin",
    specificityType: "specific",
    quantity: 1,
    isStackable: false,
    material: "leather",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-person`,
      carryMode: "on_person",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Daily travel water kept close to hand.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "valuable-item-gold-coins-1",
    characterId: sampleCharacterId,
    templateId: "valuable-template-gold-coins",
    category: "valuables",
    displayName: null,
    specificityType: "generic",
    quantity: 37,
    isStackable: true,
    material: "gold",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-person`,
      carryMode: "on_person",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Ready coin purse for daily expenses and opportunities.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "valuable-item-silver-coins-1",
    characterId: sampleCharacterId,
    templateId: "valuable-template-silver-coins",
    category: "valuables",
    displayName: null,
    specificityType: "generic",
    quantity: 140,
    isStackable: true,
    material: "silver",
    quality: "standard",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-home`,
      carryMode: "stored",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Larger reserve of silver stored in a strongbox at home.",
    isEquipped: false,
    isFavorite: null,
    acquiredFrom: null,
    statusTags: null,
  },
  {
    id: "valuable-item-gems-1",
    characterId: sampleCharacterId,
    templateId: "valuable-template-gems",
    category: "valuables",
    displayName: "Trade Gems",
    specificityType: "generic",
    quantity: 3,
    isStackable: true,
    material: "stone",
    quality: "extraordinary",
    storageAssignment: {
      locationId: `${sampleCharacterId}:loc-backpack`,
      carryMode: "backpack",
    },
    conditionState: "intact",
    durabilityCurrent: null,
    durabilityMax: null,
    encumbranceOverride: null,
    valueOverride: null,
    specialProperties: null,
    notes: "Small wrapped packet of portable trade stones.",
    isEquipped: false,
    isFavorite: true,
    acquiredFrom: null,
    statusTags: null,
  },
];

export const sampleActiveLoadout: CharacterLoadout = {
  id: `${sampleCharacterId}:loadout-active`,
  characterId: sampleCharacterId,
  name: "Current",
  isActive: true,
  wornArmorItemId: "armor-item-jerkin-1",
  readyShieldItemId: "shield-item-round-1",
  activePrimaryWeaponItemId: "weapon-item-longsword-1",
  activeSecondaryWeaponItemId: null,
  activeMissileWeaponItemId: null,
  activeAmmoItemIds: [],
  quickAccessItemIds: [],
  notes: null,
};
